name: pratical-alarm # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1' # just for humans, typically '1.2+git' or '1.3.2'
summary: a pratical alarm for linux
description: |
  A utility to configure alarm, it is minimized to tray, and at the alarm time, it sends a notification and fires an alarm sound.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  pratical-alarm:
    command: desktop-launch $SNAP/bin/main.py
    plugs:
    - home
    - desktop
    - desktop-legacy
    - wayland
    - x11
    - alsa
    - pulseaudio
    - audio-playback
    - opengl
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.8:$SNAP/usr/lib/python3.8/lib-dynload:$SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.8/site-packages:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$PYTHONPATH
      PATH: $SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$PATH
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/sox
      PULSE_SERVER: unix:/run/user/1000/pulse/native

parts:

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  pratical-alarm:
    after: [desktop-qt5, alsa-mixin]
    plugin: python
    source: .
    build-packages:
      - python3
      - python3-pyqt5
      - execstack
    stage-packages:
      - python3
      - python3-pyqt5
      - libc-bin
      - locales
      - libnotify-bin

      - alsa-utils
      - ffmpeg
      - libslang2
      - libavcodec-extra
      - libasound2
      - libgconf-2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
      - sox
      - libsox-fmt-mp3
      - libsox-fmt-pulse
    stage:
      - -usr/lib/x86_64-linux-gnu/libasound.so.2
      - -usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
    python-packages:
      - PyQt5
      - fbs
      - plyer
      - pydub

  dump-files:
    plugin: dump
    source: .
    organize:
      main.py: bin/

  alsa-mixin:
    plugin: nil
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    override-pull: |
      cat > asound.conf <<EOF
      pcm.!default {
          type pulse
          fallback "sysdefault"
          hint {
              show on
              description "Default ALSA Output (currently PulseAudio Sound Server)"
          }
      }
      ctl.!default {
          type pulse
          fallback "sysdefault"
      }
      EOF
      cat > alsa-launch <<EOF
      #!/bin/bash
      export ALSA_CONFIG_PATH="\$SNAP/etc/asound.conf"

      if [ -d "\$SNAP/usr/lib/alsa-lib" ]; then
          export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:\$SNAP/usr/lib/alsa-lib"
      elif [ -d "\$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib" ]; then
          export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:\$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib"
      fi
      export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:\$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"

      exec "\$@"
      EOF
      chmod +x alsa-launch
    override-build: |
      snapcraftctl build
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/etc asound.conf
      install -m755 -D -t $SNAPCRAFT_PART_INSTALL/snap/command-chain alsa-launch
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/lib/sox:
    bind: $SNAP/usr/lib/sox
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/sox:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/sox